Repository nil2022/CRM_App, pull requests merged in 2024-01, with the labels that each got.

#30 fix: db query from user controlled sources
  configs/auth.config.js
  controllers/auth.controller.js
  middlewares/auth.jwt.js
  middlewares/validateUserRequest.js
Labels: enhancement, javascript

#38 fix: #32 fix-code-scanning-alert-database-query-built-from-user-contr…
  controllers/user.controller.js
Labels: enhancement, javascript

#39 33-fix-code-scanning-alert-database-query-built-from-user-controlled-…
  controllers/user.controller.js
Labels: enhancement, javascript

#41 29-fix-code-scanning-alert-database-query-built-from-user-controlled-…
  middlewares/validateUserRequest.js
Labels: enhancement, javascript

#43 Create eslint.yml
  .github/workflows/eslint.yml
Labels: documentation, javascript

#44 Create njsscan.yml
  .github/workflows/njsscan.yml
Labels: enhancement

#45 27-fix-code-scanning-alert-database-query-built-from-user-controlled-…
  controllers/user.controller.js
Labels: enhancement, javascript

#47 Fix code scanning alert - Log injection
  controllers/user.controller.js
Labels: javascript

#46 31-fix-code-scanning-alert-database-query-built-from-user-controlled-…
  controllers/ticket.controller.js
  controllers/user.controller.js
Labels: enhancement, javascript

#66 fix eslint issues #38,#39,#40,#46 & #47
  controllers/ticket.controller.js
Labels: bug, javascript

#69 code fixed: issues #51,#52,#53,#54,#55
  controllers/ticket.controller.js
Labels: bug, javascript
